// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf7TQXcTd7bqrJYnq7bXNQhKEM8-LvQvM',
    appId: '1:440466092252:web:6fc61fff959285c6590419',
    messagingSenderId: '440466092252',
    projectId: 'voduyphuoc-shop',
    authDomain: 'voduyphuoc-shop.firebaseapp.com',
    storageBucket: 'voduyphuoc-shop.firebasestorage.app',
    measurementId: 'G-8ZCG59MCGD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqLOtt0xi5mVcb7ZQIbbbMMB2FaqVR4TM',
    appId: '1:440466092252:android:b08db12c80171e00590419',
    messagingSenderId: '440466092252',
    projectId: 'voduyphuoc-shop',
    storageBucket: 'voduyphuoc-shop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjGj3hMC-MYA4lXqx3tAYIEuim364jw2Q',
    appId: '1:440466092252:ios:869ea684ee9fcc7a590419',
    messagingSenderId: '440466092252',
    projectId: 'voduyphuoc-shop',
    storageBucket: 'voduyphuoc-shop.firebasestorage.app',
    iosClientId: '440466092252-s250ts9g8j7qhu5ul5j53pr5beirh2dv.apps.googleusercontent.com',
    iosBundleId: 'com.example.voduyphuoc0858',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjGj3hMC-MYA4lXqx3tAYIEuim364jw2Q',
    appId: '1:440466092252:ios:869ea684ee9fcc7a590419',
    messagingSenderId: '440466092252',
    projectId: 'voduyphuoc-shop',
    storageBucket: 'voduyphuoc-shop.firebasestorage.app',
    iosClientId: '440466092252-s250ts9g8j7qhu5ul5j53pr5beirh2dv.apps.googleusercontent.com',
    iosBundleId: 'com.example.voduyphuoc0858',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCf7TQXcTd7bqrJYnq7bXNQhKEM8-LvQvM',
    appId: '1:440466092252:web:22697153735eb1e7590419',
    messagingSenderId: '440466092252',
    projectId: 'voduyphuoc-shop',
    authDomain: 'voduyphuoc-shop.firebaseapp.com',
    storageBucket: 'voduyphuoc-shop.firebasestorage.app',
    measurementId: 'G-FD5ZYG20P5',
  );
}
